### ISSUE TITLE
Cancelled patreons

### ISSUE THREAD

**Issue by kaciexx** [AniTrack/patreon-wrapper#1]
Hi and thanks for this wrapper, 

Is it possible to see the cancelled patrons ? 

I would like to check if some subscription are still valid

Regards

**Comment by kaciexx** [comment]
Seems that there is "former_patron". Unsure what this is about

**Comment by ZSPFX** [comment]
I'm not sure how did I missed this from the notification but there seems to be "former_patron" in the Patreon API documentation.

**Comment by ZSPFX** [comment]
Just added it ae4decf
